on:
  schedule:
  - cron: '0 0/6 * * *'
  
name: Update

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.0'
    - name: Update checkver URL for VLC nightly
      run: python bin/vlc-nightly.py
    - name: Run Excavator
      uses: Ash258/Scoop-GithubActions@stable-win
      env:
        GITH_EMAIL: 88139840+petlyh@users.noreply.github.com
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SKIP_UPDATED: '1'
