on:
  schedule:
    - cron: "0 0/6 * * *"

name: Update

jobs:
  update:
    name: Update
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Excavator
        uses: Ash258/Scoop-GithubActions@stable-win
        env:
          GITH_EMAIL: 88139840+petlyh@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: "1"
